name: saltstack-rssh-formula
source: https://github.com/bechtoldt/saltstack-rssh-formula
summary: SaltStack Formula to set up and configure rssh, a restricted shell for use with OpenSSH
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
